name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Web Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: 22
          script: |
            cd grhotel/nginx/static-dashboard/gr-admin
            git pull https://${{ secrets.SERVER_GIT_USERNAME }}:${{ secrets.SERVER_TOKEN }}@github.com/AxraTech/gr-admin.git
            cd ../../../
            docker-compose build
            docker-compose down
            docker-compose up -d
            docker system prune -af